### ISSUE TITLE
[feature] 도메인 클래스 구현

### ISSUE THREAD

**Issue by yangchef1** [Sanbo-Sillok/Sanbo-Sillok-Server#2]
### ✏️Describe
각 도메인에 필요한 Entity와 enum class들을 작성합니다.

### 🚀Task
- [x] BaseEntity 작성
- [x] Post Entity 작성
- [x] Member Entity 작성
- [x] enum PostStatus 작성
- [x] enum MemberRole 작성
