### ISSUE TITLE
[refactor] 로그인 request, response 형식 변경

### ISSUE THREAD

**Issue by yangchef1** [Sanbo-Sillok/Sanbo-Sillok-Server#42]
### ✏️Describe
기존 form-data 형식에서 json으로 변경하였습니다.
해당 과정에서 jackson 라이브러리를 활용했습니다.

### 🚀Task
- [x] jackson dependencies 추가
- [x] Token DTO 구현
- [x] 로그인 시, Request 및 Response Parsing 방식 변경
- [x] SecurityConfig에 objectMapper 주입
